version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    image: events/catalogapi
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: CatalogDb
      DatabaseUser: sa
      DatabaseUserPassword: EventApi(!)
      ExternalCatalogBaseUrl: http://localhost:5060
    ports:
      - "5060:80"
    container_name: catalogapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver




  mssqlserver:
    image:  "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    container_name: catalogdb
    ports:
      - "1448:1433"
    networks:
      - backend
