version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalogservice:
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    image: events/catalogapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseServer: mssqlserver
      DatabaseName: EventCatalogDb
      DatabaseUser: sa
      DatabaseUserPassword: EventApi(!)
      ExternalCatalogBaseUrl: http://localhost:5071
    ports:
      - "5071:80"
    container_name: eventcatalogAPI
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cartservice:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: events/cartapi

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://172.16.59.179:5072
      ConnectionString: basket.data
    ports:
      - "5066:80"
    container_name: cartAPI
    networks:
      - backend
      - frontend
    depends_on:
      - basket.data
      - tokenservice
      - rabbitmq


  tokenservice:
    build:
      context: .\TokenServiceAPI
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:5085
    ports:
      - "5072:80"
    container_name: tokenAPI
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    image: events/webmvc
    container_name: webmvcevents
    environment:
      CatalogUrl: http://eventcatalogservice
      IdentityUrl: http://172.16.59.179:5072
      CallbackUrl: http://localhost:5085
      CartUrl: http://cart
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5085:80"
    networks:
      - frontend
    depends_on:
      - eventcatalogservice
      - tokenservice
      - cartservice

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    container_name: catalogDatabase
    ports:
      - "5080:1433"
    networks:
      - backend

  basket.data:
    image: redis
    ports:
      - "6378:6379"  
    networks:
      - backend 

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: myrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq/mnesia   
    networks:
      - backend 


