version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalogapi:
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    image: events/catalogapi
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventCatalogDb
      DatabaseUser: sa
      DatabaseUserPassword: EventApi(!)
      ExternalCatalogBaseUrl: http://localhost:5071
    ports:
      - "5071:80"
    container_name: eventcatalogAPI
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    image: events/webmvc
    container_name: webmvcevents
    environment:
      CatalogUrl: http://eventcatalogapi
      IdentityUrl: http://192.168.207.113:5078
      CallBackUrl: http://192.168.207.113:5085
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5085:80"
    networks:
      - frontend
    depends_on:
      - eventcatalogapi
      - tokenserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    container_name: catalogDatabase
    ports:
      - "5080:1433"
    networks:
      - backend

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:5085
    ports:
      - "5078:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver